### ISSUE TITLE
User story #1: Information

### ISSUE THREAD

**Issue by GigiLi89** [GigiLi89/pu90px#1]
**As a** user/visitor/possible customer **I can** find information about the photographer **so that** I can collect this information and see what services he offers.

**Acceptance criteria:**
1. Create a presentation text about the photographer.
2. Add some images of his work, possibly 2-3.
3. Add a button at the bottom of the page that will redirect to "Sign up" page for the free presets.

**Tasks:**
- [ ] Create a place with HTML and CSS for the presentation text to go, at the top of the page under the header/hero. 
- [ ] Create a place with HTML and CSS for the images to go under the presentation text. 
- [ ] Create a button at the bottom of the page with HTML and CSS that will redirect to "Sign up" page. The button should have the words: Sign up to get access to lightroom presets (in capital letters).
